Add third-party/elfio (#4258)
Add latest release version of elfio to third-party/elfio project for therock.

This allows us to focus for standardizing the version of these dependencies
to single version to have a better way to manage build and other type of problems.
For example we can add patch to rocprofiler-sdk to use this version instead of relying it's to download
and build elfio separately.

In addition this version of elfio contains one patch on top of the latest release version
to fix a following build error which happens with gcc and llvm compilers when they
use cpp-header files from gcc-versions like gcc 15 to
solve a following build error.

therock/build/third-party/elfio/build_elfio/
dist/include/elfio/elf_types.hpp:30:20:
error: unknown type name 'uint16_t'
9.5	   30 | using Elf_Half   = uint16_t;

This error happens because newer c/cpp standard header files shipped within gcc 15 for example
have more fine grained dependency control to other header files and vector related header files
for example does not anymore include the cstdint header file directly.

Fixes partially: https://github.com/ROCm/TheRock/issues/3517

---------

Signed-off-by: Mika Laitio <mika.laitio@amd.com>